# Generated by Django 3.1.7 on 2021-03-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210316_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDDiscountPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDISBestSeller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDISNew',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDSLug',
        ),
    ]
