# Generated by Django 3.1.7 on 2021-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_prdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDDiscountPrice',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=5, verbose_name='Discount Price'),
            preserve_default=False,
        ),
    ]
