# Generated by Django 3.1.7 on 2021-03-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210318_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CATSlug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
