# Generated by Django 3.1.7 on 2021-03-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_category_catslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDAvailable',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
    ]
