# Generated by Django 3.1.7 on 2021-03-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_prdavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
